# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-22 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500, verbose_name='Nome da disciplina')),
                ('creditos', models.IntegerField(null=True, verbose_name='Numero de creditos da disciplina')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição do perfil')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='perfil_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='cms.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500, verbose_name='Nome do professor')),
                ('matricula', models.CharField(max_length=500, verbose_name='Matricula do professor')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='rel_professor_disciplina',
            fields=[
                ('id_rel_professor_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField(null=True, verbose_name='Semestre primeiro ou segundo')),
                ('ano', models.IntegerField(null=True, verbose_name='Ano gravado')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='cms.disciplina')),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='cms.professor')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_disciplina',
            fields=[
                ('id_tipo_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500, verbose_name='Descricao do tipo de disciplina')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_professor',
            fields=[
                ('id_tipo_professor', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=500, verbose_name='Descricao do tipo de professor')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('email', models.CharField(max_length=500, verbose_name='Descrição do Relacionamento Característica Tarefa')),
                ('senha', models.CharField(max_length=500, verbose_name='Onde será salva a senha no banco de dados')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='id_tipo_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_professor', to='cms.tipo_professor'),
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='cms.usuario'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='id_tipo_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_disciplina', to='cms.tipo_disciplina'),
        ),
    ]
